environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - set CARGO_TARGET_DIR=%APPVEYOR_BUILD_FOLDER%\target
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --target %TARGET% --verbose
  - cargo build --target %TARGET% --verbose
