environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      BITS: 64
    - TARGET: i686-pc-windows-gnu
      BITS: 32

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin;C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin
  - set CARGO_TARGET_DIR=%APPVEYOR_BUILD_FOLDER%\target
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
